[package]
name = "rust-game"
version = "0.1.0"
authors = ["bryce"]

[dependencies]
sdl2 = { version = "0.31.0", features = ["bundled", "static-link"]}
gl = { path = "lib/gl" }
png = "0.13.2"
cgmath = "0.16.0"



[features]
gl_debug = ["gl/debug"]
